pag.click(665,585,duration=3)
if "." in valor:
    valorD = valor.split('.')[0]
    valorF = valor.split('.')[1]
    if len(valorF) == 2 :
        valorX = valorD.strip() + valorF.strip() + "0" 
    else :
        valorX = valorD.strip() + valorF.strip()
    #print(len(valorF))
else :
    valorX = valor.strip() + "00"
if mode == credito:
    contador += 1
    texto = 'Dizimo e oferta - n' + str(contador)
if mode == deposito:
    contadorDeposito += 1
    texto = 'Dizimo e oferta - Deposito em Dinheiro n' + str(contador)
sleep(6)
pag.click(1095,847,duration=4)
sleep(2)
pag.write('joao pessoa - jardim')
sleep(1)
pag.typewrite(['enter'])
sleep(1)
pag.click(1230,978,duration=3)
sleep(1)
pag.click(1106,1058,duration=3)
sleep(2)
pag.write('doa')
sleep(2)
pag.typewrite(['enter'])
pag.click(1138,1427,duration=1)
pag.write(texto)
pag.click(1070,1536,duration=1)
pag.write(dataDep)
pag.click(1111,1644,duration=1)
pag.write(valorX)
sleep(1)
pag.click(640,1300,duration=1)
pag.press('down')
pag.press('down')
pag.press('down')
pag.press('down')
pag.press('down')
pag.press('down')
pag.press('down')
pag.press('down')
pag.press('down')
pag.press('down')
pag.press('down')
pag.press('down')
pag.press('down')
pag.click(1141,951,duration=1)
sleep(0.5)
pag.write('PIX')
sleep(0.5)
pag.typewrite(['enter'])
pag.click(1108,1202,duration=2)
pag.write('CORA')
sleep(1.5)
pag.typewrite(['enter'])
pag.click(1052,1516,duration=2)
pag.press('down')
pag.press('down')
pag.press('down')
pag.press('down')
pag.press('down')
pag.click(644,1304,duration=1)
sleep(4)
pag.press('up')
pag.press('up')
pag.press('up')
pag.press('up')
pag.press('up')